version: "3.9"

services:
  db:
    image: postgres:16
    container_name: fitnessframework_db
    restart: always
    environment:
      POSTGRES_USER: fitness
      POSTGRES_PASSWORD: fitness
      POSTGRES_DB: fitness
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fitnessframework_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://fitness:fitness@db:5432/fitness
      SECRET_KEY: change_this_in_production

volumes:
  postgres_data:
